(* Generated by bin/prove from keycloak-authz.graph.json (java-source-graph/v1, commit 6688a3d63f59e0c4a9131bfdd556c4312799f04e,
   md5:d208acaa0dae3ac1ef242a2d5191d28b).
   Do not edit: examples/proof/dune regenerates this file and fails when it is stale.

   One definition per Java type, referents first, with its encoding. Each member
   carries the verdicts of its obligations from certificate.json. Static members
   and the instance members of enums are declared in the *_ops module types at
   the end. *)

[@@@warning "-30"]

(* Dynamic: java.lang.Object, raw types and unbounded wildcards; Class<...>. *)
type java_object
type java_class

(* External types, outside the slice: Abstract. *)
type serializable  (* java.io.Serializable *)
type throwable  (* java.lang.Throwable *)
type inet_address  (* java.net.InetAddress *)
type date  (* java.util.Date *)
type token  (* org.keycloak.Token *)
type token_category  (* org.keycloak.TokenCategory *)
type authorization_provider  (* org.keycloak.authorization.AuthorizationProvider *)
type policy_provider_admin_service  (* org.keycloak.authorization.policy.provider.PolicyProviderAdminService *)
type provider  (* org.keycloak.provider.Provider *)
type 'a1 provider_factory  (* org.keycloak.provider.ProviderFactory *)
type abstract_policy_representation  (* org.keycloak.representations.idm.authorization.AbstractPolicyRepresentation *)
type policy_representation  (* org.keycloak.representations.idm.authorization.PolicyRepresentation *)
type enum_with_stable_index  (* org.keycloak.util.EnumWithStableIndex *)

module String_map = Map.Make (String)
module String_set = Set.Make (String)

(* ---- component 36 of 36 in search order ---- *)

(* Attributes.Entry: Closures, server-spi-private/src/main/java/org/keycloak/authorization/attribute/Attributes.java:92 *)
type attributes_entry = {
  size : unit -> int;  (* size() Attributes.java:106 | PROVEN Represent, Query *)
  is_empty : unit -> bool;  (* isEmpty() Attributes.java:110 | PROVEN Represent *)
  as_string : int -> string option;  (* asString(int) Attributes.java:114 | PROVEN Represent, Nullability, Represent@param:idx, Query *)
  as_int : int -> int;  (* asInt(int) Attributes.java:122 | PROVEN Represent, Represent@param:idx, Query *)
  as_date : int -> string option -> date option;  (* asDate(int,String) Attributes.java:126 | PROVEN Nullability, Represent@param:idx, Represent@param:pattern, Nullability@param:pattern, Query; UNKNOWN Represent: outside the slice (Abstract): java.util.Date *)
  as_inet_address : int -> inet_address option;  (* asInetAddress(int) Attributes.java:134 | PROVEN Nullability, Represent@param:idx, Query; UNKNOWN Represent: outside the slice (Abstract): java.net.InetAddress *)
  as_long : int -> Int64.t;  (* asLong(int) Attributes.java:142 | PROVEN Represent, Represent@param:idx, Query *)
  as_double : int -> float;  (* asDouble(int) Attributes.java:146 | PROVEN Represent, Represent@param:idx, Query *)
}

(* ---- component 35 of 36 in search order, cyclic ---- *)

(* Attributes: Closures, server-spi-private/src/main/java/org/keycloak/authorization/attribute/Attributes.java:37 *)
type attributes = {
  to_map : unit -> string list String_map.t option;  (* toMap() Attributes.java:48 | PROVEN Represent, Nullability, Keyed, Query *)
  exists : string option -> bool;  (* exists(String) Attributes.java:56 | PROVEN Represent, Represent@param:name, Nullability@param:name, Query *)
  contains_value : string option -> string option -> bool;  (* containsValue(String,String) Attributes.java:67 | PROVEN Represent, Represent@param:name, Nullability@param:name, Represent@param:value, Nullability@param:value, Query *)
  get_value : string option -> attributes_entry option;  (* getValue(String) Attributes.java:78 | PROVEN Represent, Represent@param:name, Nullability@param:name, Query; STRENGTHENED Nullability *)
}

(* ---- component 34 of 36 in search order ---- *)

(* AuthZen: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:29 *)
type auth_zen = unit  (* no instance data *)

(* ---- component 33 of 36 in search order ---- *)

(* AuthZen.Action: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:77 *)
type auth_zen_action = {
  name : string option;  (* name AuthZen.java:77 | PROVEN Represent, Nullability *)
}

(* ---- component 32 of 36 in search order ---- *)

(* AuthZen.Resource: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:71 *)
type auth_zen_resource = {
  type_ : string option;  (* type AuthZen.java:72 | PROVEN Represent, Nullability *)
  id : string option;  (* id AuthZen.java:73 | PROVEN Represent, Nullability *)
  properties : java_object String_map.t option;  (* properties AuthZen.java:74 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
}

(* ---- component 31 of 36 in search order, cyclic ---- *)

(* AuthZen.SubjectType: Variant, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:38
   PROVEN Closed *)
type auth_zen_subject_type =
  | CLIENT
  | USER

(* ---- component 30 of 36 in search order ---- *)

(* AuthZen.Subject: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:65 *)
type auth_zen_subject = {
  type_ : auth_zen_subject_type option;  (* type AuthZen.java:66 | PROVEN Represent, Nullability *)
  id : string option;  (* id AuthZen.java:67 | PROVEN Represent, Nullability *)
  properties : java_object String_map.t option;  (* properties AuthZen.java:68 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
}

(* ---- component 29 of 36 in search order ---- *)

(* AuthZen.EvaluationItem: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:93 *)
type auth_zen_evaluation_item = {
  subject : auth_zen_subject option;  (* subject AuthZen.java:94 | PROVEN Represent, Nullability *)
  resource : auth_zen_resource option;  (* resource AuthZen.java:95 | PROVEN Represent, Nullability *)
  action : auth_zen_action option;  (* action AuthZen.java:96 | PROVEN Represent, Nullability *)
  context : java_object String_map.t option;  (* context AuthZen.java:97 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
}

(* ---- component 28 of 36 in search order ---- *)

(* AuthZen.EvaluationRequest: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:80 *)
type auth_zen_evaluation_request = {
  subject : auth_zen_subject option;  (* subject AuthZen.java:81 | PROVEN Represent, Nullability *)
  resource : auth_zen_resource option;  (* resource AuthZen.java:82 | PROVEN Represent, Nullability *)
  action : auth_zen_action option;  (* action AuthZen.java:83 | PROVEN Represent, Nullability *)
  context : java_object String_map.t option;  (* context AuthZen.java:84 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
}

(* ---- component 27 of 36 in search order ---- *)

(* AuthZen.EvaluationResponse: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:86 *)
type auth_zen_evaluation_response = {
  decision : bool;  (* decision AuthZen.java:86 | PROVEN Represent *)
  context : java_object String_map.t option;  (* context AuthZen.java:86 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
}

(* ---- component 26 of 36 in search order ---- *)

(* AuthZen.EvaluationsSemantic: Variant, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:99
   PROVEN Closed *)
type auth_zen_evaluations_semantic =
  | EXECUTE_ALL
  | DENY_ON_FIRST_DENY
  | PERMIT_ON_FIRST_PERMIT

(* ---- component 25 of 36 in search order ---- *)

(* AuthZen.Options: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:112 *)
type auth_zen_options = {
  evaluations_semantic : auth_zen_evaluations_semantic option;  (* evaluationsSemantic AuthZen.java:112 | PROVEN Represent, Nullability *)
}

(* ---- component 24 of 36 in search order ---- *)

(* AuthZen.EvaluationsRequest: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:115 *)
type auth_zen_evaluations_request = {
  subject : auth_zen_subject option;  (* subject AuthZen.java:116 | PROVEN Represent, Nullability *)
  resource : auth_zen_resource option;  (* resource AuthZen.java:117 | PROVEN Represent, Nullability *)
  action : auth_zen_action option;  (* action AuthZen.java:118 | PROVEN Represent, Nullability *)
  context : java_object String_map.t option;  (* context AuthZen.java:119 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
  options : auth_zen_options option;  (* options AuthZen.java:120 | PROVEN Represent, Nullability *)
  evaluations : auth_zen_evaluation_item list option;  (* evaluations AuthZen.java:121 | PROVEN Represent, Nullability *)
}

(* ---- component 23 of 36 in search order ---- *)

(* AuthZen.EvaluationsResponse: Record, authzen/services/src/main/java/org/keycloak/authorization/authzen/AuthZen.java:124 *)
type auth_zen_evaluations_response = {
  evaluations : auth_zen_evaluation_response list option;  (* evaluations AuthZen.java:124 | PROVEN Represent, Nullability *)
}

(* ---- component 22 of 36 in search order ---- *)

(* Decision.Effect: Variant, server-spi-private/src/main/java/org/keycloak/authorization/Decision.java:29
   PROVEN Closed *)
type decision_effect =
  | PERMIT
  | DENY

(* ---- component 21 of 36 in search order ---- *)

(* Identity: Closures, server-spi-private/src/main/java/org/keycloak/authorization/identity/Identity.java:31 *)
type identity = {
  get_id : unit -> string option;  (* getId() Identity.java:38 | PROVEN Represent, Nullability *)
  get_attributes : unit -> attributes option;  (* getAttributes() Identity.java:45 | PROVEN Represent, Nullability *)
  has_realm_role : string option -> bool;  (* hasRealmRole(String) Identity.java:54 | PROVEN Represent, Represent@param:roleName, Nullability@param:roleName, Query *)
  has_client_role : string option -> string option -> bool;  (* hasClientRole(String,String) Identity.java:66 | PROVEN Represent, Represent@param:clientId, Nullability@param:clientId, Represent@param:roleName, Nullability@param:roleName, Query *)
  has_one_client_role : string option -> string array option -> bool;  (* hasOneClientRole(String,String[]) Identity.java:78 | PROVEN Represent, Represent@param:clientId, Nullability@param:clientId, Represent@param:roleNames, Nullability@param:roleNames, Query *)
}

(* ---- component 20 of 36 in search order ---- *)

(* EvaluationContext: Record, server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/EvaluationContext.java:30 *)
type evaluation_context = {
  identity : identity option;  (* getIdentity() EvaluationContext.java:40 | PROVEN Represent, Nullability *)
  attributes : attributes option;  (* getAttributes() EvaluationContext.java:47 | PROVEN Represent, Nullability *)
}

(* ---- component 19 of 36 in search order, cyclic ---- *)

(* DecisionStrategy: Variant, core/src/main/java/org/keycloak/representations/idm/authorization/DecisionStrategy.java:30
   PROVEN Closed *)
type decision_strategy =
  | AFFIRMATIVE
  | UNANIMOUS
  | CONSENSUS

(* ---- component 18 of 36 in search order, cyclic ---- *)

(* Logic: Variant, core/src/main/java/org/keycloak/representations/idm/authorization/Logic.java:30
   PROVEN Closed *)
type logic =
  | POSITIVE
  | NEGATIVE

(* ---- component 17 of 36 in search order, cyclic ---- *)

(* PolicyEnforcementMode: Variant, core/src/main/java/org/keycloak/representations/idm/authorization/PolicyEnforcementMode.java:29
   PROVEN Closed *)
type policy_enforcement_mode =
  | ENFORCING
  | PERMISSIVE
  | DISABLED

(* ---- component 16 of 36 in search order ---- *)

(* ResourceServer: Record, server-spi-private/src/main/java/org/keycloak/authorization/model/ResourceServer.java:30 *)
type resource_server = {
  id : string option;  (* getId() ResourceServer.java:37 | PROVEN Represent, Nullability *)
  mutable allow_remote_resource_management : bool;  (* isAllowRemoteResourceManagement() ResourceServer.java:44 | PROVEN Represent; setAllowRemoteResourceManagement(boolean) ResourceServer.java:51 | PROVEN Represent@param:allowRemoteResourceManagement, Mutable *)
  mutable policy_enforcement_mode : policy_enforcement_mode option;  (* getPolicyEnforcementMode() ResourceServer.java:58 | PROVEN Represent, Nullability; setPolicyEnforcementMode(PolicyEnforcementMode) ResourceServer.java:65 | PROVEN Represent@param:enforcementMode, Nullability@param:enforcementMode, Mutable *)
  mutable decision_strategy : decision_strategy option;  (* getDecisionStrategy() ResourceServer.java:80 | PROVEN Represent, Nullability; setDecisionStrategy(DecisionStrategy) ResourceServer.java:73 | PROVEN Represent@param:decisionStrategy, Nullability@param:decisionStrategy, Mutable *)
  client_id : string option;  (* getClientId() ResourceServer.java:86 | PROVEN Represent, Nullability *)
}

(* ---- component 15 of 36 in search order ---- *)

(* Scope: Record, server-spi-private/src/main/java/org/keycloak/authorization/model/Scope.java:27 *)
type scope = {
  id : string option;  (* getId() Scope.java:49 | PROVEN Represent, Nullability *)
  mutable name : string option;  (* getName() Scope.java:56 | PROVEN Represent, Nullability; setName(String) Scope.java:63 | PROVEN Represent@param:name, Nullability@param:name, Mutable *)
  mutable display_name : string option;  (* getDisplayName() Scope.java:70 | PROVEN Represent, Nullability; setDisplayName(String) Scope.java:77 | PROVEN Represent@param:name, Nullability@param:name, Mutable *)
  mutable icon_uri : string option;  (* getIconUri() Scope.java:84 | PROVEN Represent, Nullability; setIconUri(String) Scope.java:91 | PROVEN Represent@param:iconUri, Nullability@param:iconUri, Mutable *)
  resource_server : resource_server option;  (* getResourceServer() Scope.java:98 | PROVEN Represent, Nullability *)
}

module Scope_set = Set.Make (struct type t = scope let compare = compare end)

(* ---- component 14 of 36 in search order ---- *)

(* Resource: Closures, server-spi-private/src/main/java/org/keycloak/authorization/model/Resource.java:30 *)
type resource = {
  get_id : unit -> string option;  (* getId() Resource.java:60 | PROVEN Represent, Nullability *)
  get_name : unit -> string option;  (* getName() Resource.java:67 | PROVEN Represent, Nullability *)
  set_name : string option -> unit;  (* setName(String) Resource.java:74 | PROVEN Represent@param:name, Nullability@param:name, Mutable *)
  get_display_name : unit -> string option;  (* getDisplayName() Resource.java:81 | PROVEN Represent, Nullability *)
  set_display_name : string option -> unit;  (* setDisplayName(String) Resource.java:88 | PROVEN Represent@param:name, Nullability@param:name, Mutable *)
  get_uris : unit -> String_set.t option;  (* getUris() Resource.java:95 | PROVEN Represent, Nullability, Unique *)
  update_uris : String_set.t option -> unit;  (* updateUris(Set) Resource.java:102 | PROVEN Represent@param:uri, Nullability@param:uri, Unique@param:uri, Command *)
  get_type : unit -> string option;  (* getType() Resource.java:110 | PROVEN Represent, Nullability *)
  set_type : string option -> unit;  (* setType(String) Resource.java:117 | PROVEN Represent@param:type, Nullability@param:type, Mutable *)
  get_scopes : unit -> scope list option;  (* getScopes() Resource.java:124 | PROVEN Represent, Nullability *)
  get_icon_uri : unit -> string option;  (* getIconUri() Resource.java:131 | PROVEN Represent, Nullability *)
  set_icon_uri : string option -> unit;  (* setIconUri(String) Resource.java:138 | PROVEN Represent@param:iconUri, Nullability@param:iconUri, Mutable *)
  get_resource_server : unit -> resource_server option;  (* getResourceServer() Resource.java:145 | PROVEN Represent, Nullability *)
  get_owner : unit -> string option;  (* getOwner() Resource.java:152 | PROVEN Represent, Nullability *)
  is_owner_managed_access : unit -> bool;  (* isOwnerManagedAccess() Resource.java:159 | PROVEN Represent *)
  set_owner_managed_access : bool -> unit;  (* setOwnerManagedAccess(boolean) Resource.java:166 | PROVEN Represent@param:ownerManagedAccess, Mutable *)
  update_scopes : Scope_set.t option -> unit;  (* updateScopes(Set) Resource.java:173 | PROVEN Represent@param:scopes, Nullability@param:scopes, Command; UNKNOWN Unique@param:scopes: Java equals of Scope is implementation-defined; structural compare may differ; Java equals of ResourceServer is implementation-defined; structural compare may differ *)
  get_attributes : unit -> string list String_map.t option;  (* getAttributes() Resource.java:180 | PROVEN Represent, Nullability, Keyed *)
  get_single_attribute : string option -> string option;  (* getSingleAttribute(String) Resource.java:188 | PROVEN Represent, Nullability, Represent@param:name, Nullability@param:name, Query *)
  get_attribute : string option -> string list option;  (* getAttribute(String) Resource.java:196 | PROVEN Represent, Nullability, Represent@param:name, Nullability@param:name, Query *)
  set_attribute : string option -> string list option -> unit;  (* setAttribute(String,List) Resource.java:204 | PROVEN Represent@param:name, Nullability@param:name, Represent@param:values, Nullability@param:values, Command *)
  remove_attribute : string option -> unit;  (* removeAttribute(String) Resource.java:206 | PROVEN Represent@param:name, Nullability@param:name, Command *)
}

(* ---- component 13 of 36 in search order, cyclic ---- *)

(* Policy: Closures, server-spi-private/src/main/java/org/keycloak/authorization/model/Policy.java:34 *)
type policy = {
  get_id : unit -> string option;  (* getId() Policy.java:66 | PROVEN Represent, Nullability *)
  get_type : unit -> string option;  (* getType() Policy.java:73 | PROVEN Represent, Nullability *)
  get_decision_strategy : unit -> decision_strategy option;  (* getDecisionStrategy() Policy.java:80 | PROVEN Represent, Nullability *)
  set_decision_strategy : decision_strategy option -> unit;  (* setDecisionStrategy(DecisionStrategy) Policy.java:87 | PROVEN Represent@param:decisionStrategy, Nullability@param:decisionStrategy, Mutable *)
  get_logic : unit -> logic option;  (* getLogic() Policy.java:94 | PROVEN Represent, Nullability *)
  set_logic : logic option -> unit;  (* setLogic(Logic) Policy.java:101 | PROVEN Represent@param:logic, Nullability@param:logic, Mutable *)
  get_config : unit -> string String_map.t option;  (* getConfig() Policy.java:108 | PROVEN Represent, Nullability, Keyed *)
  set_config : string String_map.t option -> unit;  (* setConfig(Map) Policy.java:116 | PROVEN Represent@param:config, Nullability@param:config, Keyed@param:config, Mutable *)
  remove_config : string option -> unit;  (* removeConfig(String) Policy.java:118 | PROVEN Represent@param:name, Nullability@param:name, Command *)
  put_config : string option -> string option -> unit;  (* putConfig(String,String) Policy.java:119 | PROVEN Represent@param:name, Nullability@param:name, Represent@param:value, Nullability@param:value, Command *)
  get_name : unit -> string option;  (* getName() Policy.java:126 | PROVEN Represent, Nullability *)
  set_name : string option -> unit;  (* setName(String) Policy.java:133 | PROVEN Represent@param:name, Nullability@param:name, Mutable *)
  get_description : unit -> string option;  (* getDescription() Policy.java:140 | PROVEN Represent, Nullability *)
  set_description : string option -> unit;  (* setDescription(String) Policy.java:147 | PROVEN Represent@param:description, Nullability@param:description, Mutable *)
  get_resource_server : unit -> resource_server option;  (* getResourceServer() Policy.java:154 | PROVEN Represent, Nullability *)
  get_associated_policies : unit -> policy list option;  (* getAssociatedPolicies() Policy.java:162 | PROVEN Represent, Nullability; REFUTED Unique: Policy must be comparable because Policy.getAssociatedPolicies() : Set<Policy>, but as Record: Policy.removeConfig(String) needs a closure; Policy.putConfig(String,String) needs a closure; Policy.addScope(Scope) needs a closure; Policy.removeScope(Scope) needs a closure; and 4 more *)
  get_resources : unit -> resource list option;  (* getResources() Policy.java:169 | PROVEN Represent, Nullability; REFUTED Unique: Resource must be comparable because Policy.getResources() : Set<Resource>, but as Record: Resource.updateUris(Set) needs a closure; Resource.updateScopes(Set) needs a closure; Resource.getSingleAttribute(String) needs a closure; Resource.getAttribute(String) needs a closure; and 2 more *)
  get_resource_names : unit -> String_set.t option;  (* getResourceNames() Policy.java:176 | PROVEN Represent, Nullability, Unique *)
  get_scopes : unit -> Scope_set.t option;  (* getScopes() Policy.java:185 | PROVEN Represent, Nullability; UNKNOWN Unique: Java equals of Scope is implementation-defined; structural compare may differ; Java equals of ResourceServer is implementation-defined; structural compare may differ *)
  get_owner : unit -> string option;  (* getOwner() Policy.java:187 | PROVEN Represent, Nullability *)
  set_owner : string option -> unit;  (* setOwner(String) Policy.java:189 | PROVEN Represent@param:owner, Nullability@param:owner, Mutable *)
  add_scope : scope option -> unit;  (* addScope(Scope) Policy.java:191 | PROVEN Represent@param:scope, Nullability@param:scope, Command *)
  remove_scope : scope option -> unit;  (* removeScope(Scope) Policy.java:193 | PROVEN Represent@param:scope, Nullability@param:scope, Command *)
  add_associated_policy : policy option -> unit;  (* addAssociatedPolicy(Policy) Policy.java:195 | PROVEN Represent@param:associatedPolicy, Nullability@param:associatedPolicy, Command *)
  remove_associated_policy : policy option -> unit;  (* removeAssociatedPolicy(Policy) Policy.java:197 | PROVEN Represent@param:associatedPolicy, Nullability@param:associatedPolicy, Command *)
  add_resource : resource option -> unit;  (* addResource(Resource) Policy.java:199 | PROVEN Represent@param:resource, Nullability@param:resource, Command *)
  remove_resource : resource option -> unit;  (* removeResource(Resource) Policy.java:201 | PROVEN Represent@param:resource, Nullability@param:resource, Command *)
  get_resource_type : unit -> string option;  (* getResourceType() Policy.java:203 | PROVEN Represent, Nullability *)
  set_resource_type : string option -> unit;  (* setResourceType(String) Policy.java:207 | PROVEN Represent@param:resourceType, Nullability@param:resourceType, Mutable *)
}

(* ---- component 12 of 36 in search order ---- *)

(* Realm: Closures, server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/Realm.java:27 *)
type realm = {
  is_user_in_group : string option -> string option -> bool;  (* isUserInGroup(String,String) Realm.java:40 | PROVEN Represent, Represent@param:id, Nullability@param:id, Represent@param:group, Nullability@param:group, Query *)
  is_user_in_group_3 : string option -> string option -> bool -> bool;  (* isUserInGroup(String,String,boolean) Realm.java:52 | PROVEN Represent, Represent@param:id, Nullability@param:id, Represent@param:group, Nullability@param:group, Represent@param:checkParent, Query *)
  is_user_in_realm_role : string option -> string option -> bool;  (* isUserInRealmRole(String,String) Realm.java:61 | PROVEN Represent, Represent@param:id, Nullability@param:id, Represent@param:role, Nullability@param:role, Query *)
  is_user_in_client_role : string option -> string option -> string option -> bool;  (* isUserInClientRole(String,String,String) Realm.java:71 | PROVEN Represent, Represent@param:id, Nullability@param:id, Represent@param:clientId, Nullability@param:clientId, Represent@param:role, Nullability@param:role, Query *)
  is_group_in_role : string option -> string option -> bool;  (* isGroupInRole(String,String) Realm.java:80 | PROVEN Represent, Represent@param:group, Nullability@param:group, Represent@param:role, Nullability@param:role, Query *)
  get_user_realm_roles : string option -> string list option;  (* getUserRealmRoles(String) Realm.java:88 | PROVEN Represent, Nullability, Represent@param:id, Nullability@param:id, Query *)
  get_user_client_roles : string option -> string option -> string list option;  (* getUserClientRoles(String,String) Realm.java:97 | PROVEN Represent, Nullability, Represent@param:id, Nullability@param:id, Represent@param:clientId, Nullability@param:clientId, Query *)
  get_user_groups : string option -> string list option;  (* getUserGroups(String) Realm.java:105 | PROVEN Represent, Nullability, Represent@param:id, Nullability@param:id, Query *)
  get_user_attributes : string option -> string list String_map.t option;  (* getUserAttributes(String) Realm.java:113 | PROVEN Represent, Nullability, Keyed, Represent@param:id, Nullability@param:id, Query *)
}

(* ---- component 11 of 36 in search order ---- *)

(* ResourcePermission: Closures, server-spi-private/src/main/java/org/keycloak/authorization/permission/ResourcePermission.java:39 *)
type resource_permission = {
  get_resource_type : unit -> string option;  (* getResourceType() ResourcePermission.java:77 | PROVEN Represent, Nullability *)
  get_resource : unit -> resource option;  (* getResource() ResourcePermission.java:86 | PROVEN Represent, Nullability *)
  get_scopes : unit -> scope list option;  (* getScopes() ResourcePermission.java:95 | PROVEN Represent, Nullability *)
  get_resource_server : unit -> resource_server option;  (* getResourceServer() ResourcePermission.java:104 | PROVEN Represent, Nullability *)
  get_claims : unit -> String_set.t String_map.t option;  (* getClaims() ResourcePermission.java:113 | PROVEN Represent, Nullability, Keyed, Unique@return/1 *)
  add_claim : string option -> string option -> bool;  (* addClaim(String,String) ResourcePermission.java:128 | PROVEN Represent, Represent@param:name, Nullability@param:name, Represent@param:value, Nullability@param:value, Query *)
  remove_claim : string option -> unit;  (* removeClaim(String) ResourcePermission.java:141 | PROVEN Represent@param:name, Nullability@param:name, Command *)
  add_scope : scope option -> unit;  (* addScope(Scope) ResourcePermission.java:147 | PROVEN Represent@param:scope, Nullability@param:scope, Command *)
  add_claims : String_set.t String_map.t option -> unit;  (* addClaims(Map) ResourcePermission.java:159 | PROVEN Represent@param:claims, Nullability@param:claims, Keyed@param:claims, Unique@param:claims/1, Command *)
  set_granted : bool -> unit;  (* setGranted(boolean) ResourcePermission.java:166 | PROVEN Represent@param:granted, Mutable *)
  is_granted : unit -> bool;  (* isGranted() ResourcePermission.java:170 | PROVEN Represent *)
}

(* ---- component 10 of 36 in search order ---- *)

(* Evaluation: Object, server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/Evaluation.java:34 *)
type evaluation = <
  get_permission : resource_permission option;  (* getPermission() Evaluation.java:41 | PROVEN Represent, Nullability *)
  get_context : evaluation_context option;  (* getContext() Evaluation.java:48 | PROVEN Represent, Nullability *)
  get_policy : policy option;  (* getPolicy() Evaluation.java:55 | PROVEN Represent, Nullability *)
  get_realm : realm option;  (* getRealm() Evaluation.java:62 | PROVEN Represent, Nullability *)
  get_authorization_provider : authorization_provider option;  (* getAuthorizationProvider() Evaluation.java:64 | PROVEN Nullability; UNKNOWN Represent: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  grant : unit -> unit;  (* grant() Evaluation.java:69 | PROVEN Command *)
  deny : unit -> unit;  (* deny() Evaluation.java:74 | PROVEN Command *)
  deny_if_no_effect : unit -> unit;  (* denyIfNoEffect() Evaluation.java:79 | PROVEN Command *)
  get_parent_policy : policy option;  (* getParentPolicy() Evaluation.java:86 | PROVEN Represent, Nullability *)
  get_effect : decision_effect option;  (* getEffect() Evaluation.java:88 | PROVEN Represent, Nullability *)
  set_effect : decision_effect option -> unit;  (* setEffect(Decision.Effect) Evaluation.java:90 | PROVEN Represent@param:effect, Nullability@param:effect, Mutable *)
  is_granted : policy option -> scope option -> bool;  (* isGranted(Policy,Scope) Evaluation.java:99 | PROVEN Represent, Represent@param:grantedPolicy, Nullability@param:grantedPolicy, Represent@param:grantedScope, Nullability@param:grantedScope, Query *)
  is_denied : policy option -> scope option -> bool;  (* isDenied(Policy,Scope) Evaluation.java:110 | PROVEN Represent, Represent@param:deniedPolicy, Nullability@param:deniedPolicy, Represent@param:deniedScope, Nullability@param:deniedScope, Query *)
>

(* ---- component 9 of 36 in search order ---- *)

(* Decision: Closures, server-spi-private/src/main/java/org/keycloak/authorization/Decision.java:27
   PROVEN Bounded@<D extends Evaluation> *)
type 'd decision = {
  on_decision : 'd option -> unit;  (* onDecision(D) Decision.java:34 | PROVEN Represent@param:evaluation, Nullability@param:evaluation, Command *)
  on_error : throwable option -> unit;  (* onError(Throwable) Decision.java:36 | PROVEN Nullability@param:cause, Command; UNKNOWN Represent@param:cause: outside the slice (Abstract): java.lang.Throwable *)
  on_complete : unit -> unit;  (* onComplete() Decision.java:40 | PROVEN Command *)
  on_complete_1 : resource_permission option -> unit;  (* onComplete(ResourcePermission) Decision.java:43 | PROVEN Represent@param:permission, Nullability@param:permission, Command *)
  is_evaluated : string option -> bool;  (* isEvaluated(String) Decision.java:52 | PROVEN Represent, Represent@param:scope, Nullability@param:scope, Query *)
}
constraint 'd = <
  get_permission : resource_permission option;
  get_context : evaluation_context option;
  get_policy : policy option;
  get_realm : realm option;
  get_authorization_provider : authorization_provider option;
  grant : unit -> unit;
  deny : unit -> unit;
  deny_if_no_effect : unit -> unit;
  get_parent_policy : policy option;
  get_effect : decision_effect option;
  set_effect : decision_effect option -> unit;
  is_granted : policy option -> scope option -> bool;
  is_denied : policy option -> scope option -> bool;
  .. >  (* the methods of Evaluation *)

(* ---- component 8 of 36 in search order, cyclic ---- *)

(* JsonWebToken: Closures, core/src/main/java/org/keycloak/representations/JsonWebToken.java:43 *)
type json_web_token = {
  mutable id : string option;  (* id JsonWebToken.java:49 | PROVEN Represent, Nullability, Mutable *)
  mutable exp : Int64.t option;  (* exp JsonWebToken.java:51 | PROVEN Represent, Nullability, Mutable *)
  mutable nbf : Int64.t option;  (* nbf JsonWebToken.java:52 | PROVEN Represent, Nullability, Mutable *)
  mutable iat : Int64.t option;  (* iat JsonWebToken.java:53 | PROVEN Represent, Nullability, Mutable *)
  mutable issuer : string option;  (* issuer JsonWebToken.java:56 | PROVEN Represent, Nullability, Mutable *)
  mutable audience : string array option;  (* audience JsonWebToken.java:59 | PROVEN Represent, Nullability, Mutable *)
  mutable subject : string option;  (* subject JsonWebToken.java:61 | PROVEN Represent, Nullability, Mutable *)
  mutable type_ : string option;  (* type JsonWebToken.java:63 | PROVEN Represent, Nullability, Mutable *)
  mutable issued_for : string option;  (* issuedFor JsonWebToken.java:65 | PROVEN Represent, Nullability, Mutable *)
  mutable other_claims : java_object String_map.t option;  (* otherClaims JsonWebToken.java:66 | PROVEN Represent, Nullability, Keyed, Mutable; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
  get_id : unit -> string option;  (* getId() JsonWebToken.java:68 | PROVEN Represent, Nullability *)
  id_1 : string option -> json_web_token option;  (* id(String) JsonWebToken.java:72 | PROVEN Represent, Nullability, Represent@param:id, Nullability@param:id, Query *)
  get_exp : unit -> Int64.t option;  (* getExp() JsonWebToken.java:77 | PROVEN Represent, Nullability *)
  exp_1 : Int64.t option -> json_web_token option;  (* exp(Long) JsonWebToken.java:81 | PROVEN Represent, Nullability, Represent@param:exp, Nullability@param:exp, Query *)
  is_expired : unit -> bool;  (* isExpired() JsonWebToken.java:87 | PROVEN Represent *)
  get_nbf : unit -> Int64.t option;  (* getNbf() JsonWebToken.java:91 | PROVEN Represent, Nullability *)
  nbf_1 : Int64.t option -> json_web_token option;  (* nbf(Long) JsonWebToken.java:95 | PROVEN Represent, Nullability, Represent@param:nbf, Nullability@param:nbf, Query *)
  is_not_before : Int64.t -> bool;  (* isNotBefore(long) JsonWebToken.java:101 | PROVEN Represent, Represent@param:allowedTimeSkew, Query *)
  is_active : unit -> bool;  (* isActive() JsonWebToken.java:120 | PROVEN Represent *)
  is_active_1 : int -> bool;  (* isActive(int) JsonWebToken.java:125 | PROVEN Represent, Represent@param:allowedTimeSkew, Query *)
  is_issued_before_session_start : Int64.t -> bool;  (* isIssuedBeforeSessionStart(long) JsonWebToken.java:134 | PROVEN Represent, Represent@param:sessionStarted, Query *)
  get_iat : unit -> Int64.t option;  (* getIat() JsonWebToken.java:138 | PROVEN Represent, Nullability *)
  issued_now : unit -> json_web_token option;  (* issuedNow() JsonWebToken.java:146 | PROVEN Represent, Nullability, Query *)
  issued_now_with_ttl : int -> json_web_token option;  (* issuedNowWithTTL(int) JsonWebToken.java:156 | PROVEN Represent, Nullability, Represent@param:ttl, Query *)
  iat_1 : Int64.t option -> json_web_token option;  (* iat(Long) JsonWebToken.java:162 | PROVEN Represent, Nullability, Represent@param:iat, Nullability@param:iat, Query *)
  get_issuer : unit -> string option;  (* getIssuer() JsonWebToken.java:167 | PROVEN Represent, Nullability *)
  issuer_1 : string option -> json_web_token option;  (* issuer(String) JsonWebToken.java:171 | PROVEN Represent, Nullability, Represent@param:issuer, Nullability@param:issuer, Query *)
  get_audience : unit -> string array option;  (* getAudience() JsonWebToken.java:177 | PROVEN Represent, Nullability *)
  has_audience : string option -> bool;  (* hasAudience(String) JsonWebToken.java:181 | PROVEN Represent, Represent@param:audience, Nullability@param:audience, Query *)
  has_any_audience : string list option -> bool;  (* hasAnyAudience(List) JsonWebToken.java:191 | PROVEN Represent, Represent@param:audiences, Nullability@param:audiences, Query *)
  audience_1 : string array option -> json_web_token option;  (* audience(String[]) JsonWebToken.java:207 | PROVEN Represent, Nullability, Represent@param:audience, Nullability@param:audience, Query *)
  add_audience : string option -> json_web_token option;  (* addAudience(String) JsonWebToken.java:212 | PROVEN Represent, Nullability, Represent@param:audience, Nullability@param:audience, Query *)
  get_subject : unit -> string option;  (* getSubject() JsonWebToken.java:230 | PROVEN Represent, Nullability *)
  subject_1 : string option -> json_web_token option;  (* subject(String) JsonWebToken.java:234 | PROVEN Represent, Nullability, Represent@param:subject, Nullability@param:subject, Query *)
  set_subject : string option -> unit;  (* setSubject(String) JsonWebToken.java:239 | PROVEN Represent@param:subject, Nullability@param:subject, Mutable *)
  get_type : unit -> string option;  (* getType() JsonWebToken.java:243 | PROVEN Represent, Nullability *)
  type_1 : string option -> json_web_token option;  (* type(String) JsonWebToken.java:247 | PROVEN Represent, Nullability, Represent@param:type, Nullability@param:type, Query *)
  get_issued_for : unit -> string option;  (* getIssuedFor() JsonWebToken.java:257 | PROVEN Represent, Nullability *)
  issued_for_1 : string option -> json_web_token option;  (* issuedFor(String) JsonWebToken.java:261 | PROVEN Represent, Nullability, Represent@param:issuedFor, Nullability@param:issuedFor, Query *)
  get_other_claims : unit -> java_object String_map.t option;  (* getOtherClaims() JsonWebToken.java:272 | PROVEN Represent, Nullability, Keyed; UNKNOWN Dynamic: Object: the Java type states no fact to preserve *)
  set_other_claims : string option -> java_object option -> unit;  (* setOtherClaims(String,Object) JsonWebToken.java:277 | PROVEN Represent@param:name, Nullability@param:name, Represent@param:value, Nullability@param:value, Command; UNKNOWN Dynamic@param:value: Object: the Java type states no fact to preserve *)
  get_category : unit -> token_category option;  (* getCategory() JsonWebToken.java:282 | PROVEN Nullability; UNKNOWN Represent: outside the slice (Abstract): org.keycloak.TokenCategory *)
  equals : java_object option -> bool;  (* equals(Object) JsonWebToken.java:287 | PROVEN Represent, Represent@param:o, Nullability@param:o, Query; UNKNOWN Dynamic@param:o: Object: the Java type states no fact to preserve *)
  hash_code : unit -> int;  (* hashCode() JsonWebToken.java:306 | PROVEN Represent, Query *)
  to_string : unit -> string option;  (* toString() JsonWebToken.java:321 | PROVEN Represent, Nullability, Query *)
}

(* ---- component 7 of 36 in search order ---- *)

(* PermissionTicket: Record, server-spi-private/src/main/java/org/keycloak/authorization/model/PermissionTicket.java:22 *)
type permission_ticket = {
  id : string option;  (* getId() PermissionTicket.java:57 | PROVEN Represent, Nullability *)
  owner : string option;  (* getOwner() PermissionTicket.java:64 | PROVEN Represent, Nullability *)
  requester : string option;  (* getRequester() PermissionTicket.java:66 | PROVEN Represent, Nullability *)
  resource : resource option;  (* getResource() PermissionTicket.java:73 | PROVEN Represent, Nullability *)
  scope : scope option;  (* getScope() PermissionTicket.java:80 | PROVEN Represent, Nullability *)
  granted : bool;  (* isGranted() PermissionTicket.java:82 | PROVEN Represent *)
  created_timestamp : Int64.t option;  (* getCreatedTimestamp() PermissionTicket.java:84 | PROVEN Represent, Nullability *)
  mutable granted_timestamp : Int64.t option;  (* getGrantedTimestamp() PermissionTicket.java:86 | PROVEN Represent, Nullability; setGrantedTimestamp(Long) PermissionTicket.java:87 | PROVEN Represent@param:millis, Nullability@param:millis, Mutable *)
  resource_server : resource_server option;  (* getResourceServer() PermissionTicket.java:94 | PROVEN Represent, Nullability *)
  mutable policy : policy option;  (* getPolicy() PermissionTicket.java:96 | PROVEN Represent, Nullability; setPolicy(Policy) PermissionTicket.java:98 | PROVEN Represent@param:policy, Nullability@param:policy, Mutable *)
}

(* ---- component 6 of 36 in search order ---- *)

(* PermissionTicket.FilterOption: Variant, server-spi-private/src/main/java/org/keycloak/authorization/model/PermissionTicket.java:24
   PROVEN Closed *)
type permission_ticket_filter_option =
  | ID
  | RESOURCE_ID
  | RESOURCE_NAME
  | SCOPE_ID
  | SCOPE_IS_NULL
  | OWNER
  | GRANTED
  | REQUESTER
  | REQUESTER_IS_NULL
  | POLICY_IS_NOT_NULL
  | POLICY_ID
  | IS_ADMIN

(* ---- component 5 of 36 in search order ---- *)

(* Policy.FilterOption: Variant, server-spi-private/src/main/java/org/keycloak/authorization/model/Policy.java:36
   PROVEN Closed *)
type policy_filter_option =
  | ID
  | PERMISSION
  | OWNER
  | ANY_OWNER
  | RESOURCE_ID
  | SCOPE_ID
  | CONFIG
  | TYPE
  | NAME

(* ---- component 4 of 36 in search order ---- *)

(* PolicyProvider: Closures, server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PolicyProvider.java:26
   PROVEN Open *)
type policy_provider = {
  evaluate : evaluation option -> unit;  (* evaluate(Evaluation) PolicyProvider.java:28 | PROVEN Represent@param:evaluation, Nullability@param:evaluation, Command *)
}

(* ---- component 3 of 36 in search order ---- *)

(* PolicyProviderFactory: Closures, server-spi-private/src/main/java/org/keycloak/authorization/policy/provider/PolicyProviderFactory.java:31
   PROVEN Open; REFUTED Bounded@<R extends AbstractPolicyRepresentation>: OCaml type parameters carry no bounds: AbstractPolicyRepresentation is outside the slice (Abstract), so R cannot be row-constrained *)
type 'r policy_provider_factory = {
  get_name : unit -> string option;  (* getName() PolicyProviderFactory.java:33 | PROVEN Represent, Nullability *)
  get_group : unit -> string option;  (* getGroup() PolicyProviderFactory.java:35 | PROVEN Represent, Nullability *)
  get_description : unit -> string option;  (* getDescription() PolicyProviderFactory.java:37 | PROVEN Represent; STRENGTHENED Nullability *)
  get_code : unit -> string option;  (* getCode() PolicyProviderFactory.java:41 | PROVEN Represent; STRENGTHENED Nullability *)
  is_internal : unit -> bool;  (* isInternal() PolicyProviderFactory.java:45 | PROVEN Represent *)
  create : authorization_provider option -> policy_provider option;  (* create(AuthorizationProvider) PolicyProviderFactory.java:49 | PROVEN Represent, Nullability, Nullability@param:authorization, Query; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  to_representation : policy option -> authorization_provider option -> 'r option;  (* toRepresentation(Policy,AuthorizationProvider) PolicyProviderFactory.java:51 | PROVEN Represent, Nullability, Represent@param:policy, Nullability@param:policy, Nullability@param:authorization, Query; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  get_representation_type : unit -> java_class option;  (* getRepresentationType() PolicyProviderFactory.java:53 | PROVEN Represent, Nullability; UNKNOWN Dynamic: Class<R>: the Java type states no fact to preserve *)
  on_create : policy option -> 'r option -> authorization_provider option -> unit;  (* onCreate(Policy,R,AuthorizationProvider) PolicyProviderFactory.java:55 | PROVEN Represent@param:policy, Nullability@param:policy, Represent@param:representation, Nullability@param:representation, Nullability@param:authorization, Command; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  on_update : policy option -> 'r option -> authorization_provider option -> unit;  (* onUpdate(Policy,R,AuthorizationProvider) PolicyProviderFactory.java:59 | PROVEN Represent@param:policy, Nullability@param:policy, Represent@param:representation, Nullability@param:representation, Nullability@param:authorization, Command; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  on_remove : policy option -> authorization_provider option -> unit;  (* onRemove(Policy,AuthorizationProvider) PolicyProviderFactory.java:63 | PROVEN Represent@param:policy, Nullability@param:policy, Nullability@param:authorization, Command; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  on_import : policy option -> policy_representation option -> authorization_provider option -> unit;  (* onImport(Policy,PolicyRepresentation,AuthorizationProvider) PolicyProviderFactory.java:67 | PROVEN Represent@param:policy, Nullability@param:policy, Nullability@param:representation, Nullability@param:authorization, Command; UNKNOWN Represent@param:representation: outside the slice (Abstract): org.keycloak.representations.idm.authorization.PolicyRepresentation; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  on_export : policy option -> policy_representation option -> authorization_provider option -> unit;  (* onExport(Policy,PolicyRepresentation,AuthorizationProvider) PolicyProviderFactory.java:71 | PROVEN Represent@param:policy, Nullability@param:policy, Nullability@param:representation, Nullability@param:authorizationProvider, Command; UNKNOWN Represent@param:representation: outside the slice (Abstract): org.keycloak.representations.idm.authorization.PolicyRepresentation; UNKNOWN Represent@param:authorizationProvider: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
  get_admin_resource : resource_server option -> authorization_provider option -> policy_provider_admin_service option;  (* getAdminResource(ResourceServer,AuthorizationProvider) PolicyProviderFactory.java:74 | PROVEN Represent@param:resourceServer, Nullability@param:resourceServer, Nullability@param:authorization, Query; STRENGTHENED Nullability; UNKNOWN Represent: outside the slice (Abstract): org.keycloak.authorization.policy.provider.PolicyProviderAdminService; UNKNOWN Represent@param:authorization: outside the slice (Abstract): org.keycloak.authorization.AuthorizationProvider *)
}

(* ---- component 2 of 36 in search order ---- *)

(* Resource.FilterOption: Variant, server-spi-private/src/main/java/org/keycloak/authorization/model/Resource.java:32
   PROVEN Closed *)
type resource_filter_option =
  | ID
  | NAME
  | EXACT_NAME
  | OWNER
  | TYPE
  | URI
  | URI_NOT_NULL
  | OWNER_MANAGED_ACCESS
  | SCOPE_ID

(* ---- component 1 of 36 in search order ---- *)

(* Scope.FilterOption: Variant, server-spi-private/src/main/java/org/keycloak/authorization/model/Scope.java:29
   PROVEN Closed *)
type scope_filter_option =
  | ID
  | NAME

(* ---- static members and enum members ---- *)

module type Attributes_ops = sig
  val from : string list String_map.t option -> attributes option  (* static from(Map) Attributes.java:39 | PROVEN Represent, Nullability, Represent@param:attributes, Nullability@param:attributes, Keyed@param:attributes, Query *)
end

module type Auth_zen_ops = sig
  val authzen_access_path : string option  (* static AUTHZEN_ACCESS_PATH AuthZen.java:31 | PROVEN Represent, Nullability *)
  val evaluation_path : string option  (* static EVALUATION_PATH AuthZen.java:32 | PROVEN Represent, Nullability *)
  val evaluations_path : string option  (* static EVALUATIONS_PATH AuthZen.java:33 | PROVEN Represent, Nullability *)
end

module type Auth_zen_subject_type_ops = sig
  val get_value : auth_zen_subject_type -> string option  (* getValue() AuthZen.java:49 | PROVEN Represent, Nullability *)
  val from_value : string option -> auth_zen_subject_type option  (* static fromValue(String) AuthZen.java:54 | PROVEN Represent, Nullability, Represent@param:value, Nullability@param:value, Query *)
end

module type Decision_strategy_ops = sig
  val get_stable_index : decision_strategy -> int  (* getStableIndex() DecisionStrategy.java:57 | PROVEN Represent *)
  val value_of_integer : int option -> decision_strategy option  (* static valueOfInteger(Integer) DecisionStrategy.java:61 | PROVEN Represent, Represent@param:id, Nullability@param:id, Query; STRENGTHENED Nullability *)
end

module type Evaluation_context_ops = sig
  val realm_name_attribute : string option  (* static REALM_NAME_ATTRIBUTE EvaluationContext.java:32 | PROVEN Represent, Nullability *)
  val client_id_attribute : string option  (* static CLIENT_ID_ATTRIBUTE EvaluationContext.java:33 | PROVEN Represent, Nullability *)
end

module type Json_web_token_ops = sig
  val azp : string option  (* static AZP JsonWebToken.java:44 | PROVEN Represent, Nullability *)
  val aud : string option  (* static AUD JsonWebToken.java:45 | PROVEN Represent, Nullability *)
  val subject : string option  (* static SUBJECT JsonWebToken.java:46 | PROVEN Represent, Nullability *)
end

module type Logic_ops = sig
  val get_stable_index : logic -> int  (* getStableIndex() Logic.java:51 | PROVEN Represent *)
  val value_of_integer : int option -> logic option  (* static valueOfInteger(Integer) Logic.java:55 | PROVEN Represent, Represent@param:id, Nullability@param:id, Query; STRENGTHENED Nullability *)
end

module type Permission_ticket_filter_option_ops = sig
  val get_name : permission_ticket_filter_option -> string option  (* getName() PermissionTicket.java:47 | PROVEN Represent, Nullability *)
end

module type Policy_ops = sig
  val config_separator : string option  (* static CONFIG_SEPARATOR Policy.java:59 | PROVEN Represent, Nullability *)
end

module type Policy_filter_option_ops = sig
  val empty_filter : string array option  (* static EMPTY_FILTER Policy.java:47 | PROVEN Represent, Nullability *)
  val get_name : policy_filter_option -> string option  (* getName() Policy.java:54 | PROVEN Represent, Nullability *)
end

module type Policy_enforcement_mode_ops = sig
  val get_stable_index : policy_enforcement_mode -> int  (* getStableIndex() PolicyEnforcementMode.java:55 | PROVEN Represent *)
  val value_of_integer : int option -> policy_enforcement_mode option  (* static valueOfInteger(Integer) PolicyEnforcementMode.java:59 | PROVEN Represent, Represent@param:id, Nullability@param:id, Query; STRENGTHENED Nullability *)
end

module type Resource_filter_option_ops = sig
  val get_name : resource_filter_option -> string option  (* getName() Resource.java:49 | PROVEN Represent, Nullability *)
end

module type Scope_filter_option_ops = sig
  val get_name : scope_filter_option -> string option  (* getName() Scope.java:39 | PROVEN Represent, Nullability *)
end

